// <auto-generated />
namespace CST324_TermProject_RideShare.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CreditCardToString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreditCardToString));
        
        string IMigrationMetadata.Id
        {
            get { return "201812050316384_CreditCardToString"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
